# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    # branches: ["main"]
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install deps
        run: pnpm i
      - name: Run test
        run: pnpm test
      - run: pnpm run doc
      - name: Make GitHub links absolute
        run:
          shopt -s globstar;
          sed
          --in-place
          --expression='s:/develop/docs/:/${{ github.sha }}/docs/:g'
          --expression='s:<img src="docs/assets/:<img src="media/:g'
          web/**/*.html;
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './web'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
